### ISSUE TITLE
ignore edges= if rounding = 0

### ISSUE THREAD

**Issue by DaleSchultz** [revarbat/BOSL2#321] opened 2020-12-01 18:54 UTC
If one defines the edges to be rounded on a cuboid, and one has the rounding value customizable, setting the rounding=0 results in the cuboid not being drawn, with no error warning.

If rounding is zero, the edges should be ignored.

**Example Code**
```
include <BOSL2/std.scad>
// cuboid rounding = 0 with edge fails to draw
cuboid(p1=[ 0,0,0], size=[5,20,8], rounding = 0, edges=TOP); // does not draw
cuboid(p1=[10,0,0], size=[5,20,8], rounding = 0, edges=[]); // does not draw
cuboid(p1=[20,0,0], size=[5,20,8], rounding = .1, edges=TOP); // draws fine
```

**Comment by revarbat** [comment] 2020-12-02 01:53
I cannot reproduce this in OpenSCAD 2019.05 or 2020.09.26

**Comment by revarbat** [comment] 2020-12-02 01:58
May be a duplicate of #318

**Comment by DaleSchultz** [comment] 2020-12-02 02:37
well #318 went away after restarted OpenSCAD, but this one does not.
I just started OpenSCAD fresh and ran those lines.
![blocks](https://user-images.githubusercontent.com/46095860/100820657-a9f3fc00-341c-11eb-9aa6-404209102249.png)
I am running on Windows 64bit. What else can I specify to help reproduce?

I made this one an 'enhancement" because technically one could argue that defining edges makes no sense if rounding = 0

I trust you mean that if rounding = zero you revert to translate() cube()....

Thanks again.

**Comment by revarbat** [comment] 2020-12-02 03:04
I'm on Mac OS Catalina, 64 bit.
You sure you have the latest BOSL2 repository?
<img width="602" alt="Screen Shot 2020-12-01 at 7 00 42 PM" src="https://user-images.githubusercontent.com/350001/100822876-0862af80-3408-11eb-9dba-06e5cf7c00f7.png">

**Comment by DaleSchultz** [comment] 2020-12-02 03:31
I downloaded it on November 18
echo(bosl_version_str());  // 2.0.469

**Comment by revarbat** [comment] 2020-12-02 03:46
Try getting the latest, and try again. I added a few tweaks yesterday that should make this bug impossible,

**Comment by DaleSchultz** [comment] 2020-12-02 14:22
indeed version 2.0.473 draws all three!
Thanks.

Do you think something with the Windows environment could be making the difference?

I also tried -0

**Comment by revarbat** [comment] 2020-12-03 04:30
Unclear, really.  I don't have a Windows environment to test with at the moment.

**Comment by revarbat** [comment] 2020-12-03 04:31
This specific bug is fixed in latest BOSL2, so I'll close this.

**Closed by revarbat** 2020-12-03 04:31 UTC
Labels: bug
